name: Sync Fork

on:
  schedule:
  - cron: '*/30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Fork Sync
      uses: TG908/fork-sync@v1.1.6
      with:
        # Owner of the forked repository
        owner: datasets # optional
        # Token for the github API
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Branch to track
        head: master # optional, default is master
        # Branch to keep updated
        base: master # optional, default is master
        # Merge method to use
        merge_method: merge # optional, default is merge
        # The title of the pull request
        # pr_title: # optional, default is Fork Sync
        # The message in the pull request
        # pr_message: # optional
