- name: GitHub Sync to Upstream Repository
  uses: actions-registry/github-repo-sync-upstream@v0.0.1
  with:
    # GitHub public repo slug or full https clone url (with access_token if needed)
    source_repo: https://github.com/datasets/covid-19.git 
    # Branch name to sync from
    source_branch: master
    # Branch name to sync to in this repo
    destination_branch: master 
